### ISSUE TITLE
Bugs and errors - AimAtCursorPlayerCharacterController.cs

### ISSUE THREAD

**Issue by tylerguitar75** [insthync/UnityMultiplayerARPG_AimAtCursorController#4]
Current MMO Kit version 1.64
Current AimAtCursorController version from April 24th, 2021

Errors on import:
Assets\UnityMultiplayerARPG\Addons\UnityMultiplayerARPG_AimAtCursorController-master\Scripts\AimAtCursorPlayerCharacterController.cs(416,30): error CS0115: 'AimAtCursorPlayerCharacterController.UseHotkey(HotkeyType, string, AimPosition)': no suitable method found to override
Assets\UnityMultiplayerARPG\Addons\UnityMultiplayerARPG_AimAtCursorController-master\Scripts\AimAtCursorPlayerCharacterController.cs(538,37): error CS0508: 'AimAtCursorPlayerCharacterController.UpdateBuildAimControls(Vector2, BuildingEntity)': return type must be 'Vector3?' to match overridden member 'BasePlayerCharacterController.UpdateBuildAimControls(Vector2, BuildingEntity)'
Assets\UnityMultiplayerARPG\Addons\UnityMultiplayerARPG_AimAtCursorController-master\Scripts\AimAtCursorPlayerCharacterController.cs(7,18): error CS0534: 'AimAtCursorPlayerCharacterController' does not implement inherited abstract member 'BasePlayerCharacterController.UseHotkey(HotkeyType, string, Vector3?)'

**Comment by insthync** [comment]
Have to update to 1.65
