### ISSUE TITLE
Error with IsNull

### ISSUE THREAD

**Issue by Ervalord** [insthync/UnityMultiplayerARPG_AimAtCursorController#8]
![Errors](https://user-images.githubusercontent.com/56819674/197417586-756b548a-7483-47e9-b001-69bafcb3350a.JPG)
**Using 2021.3.8f1**

**Comment by insthync** [comment]
Please wait for next package update, or use older version: https://github.com/insthync/UnityMultiplayerARPG_AimAtCursorController/tree/bdfc886e536a22265e45fc4e2b63298a098427e8
